import { Stage } from '@/types/plot';

export const BUILD_STAGES: Omit<Stage, 'id' | 'status' | 'notes' | 'issues' | 'delays' | 'plannedStartDate' | 'plannedEndDate' | 'actualStartDate' | 'actualEndDate'>[] = [
  { name: 'Foundations', duration: 2 },
  { name: 'Substructure brickwork', duration: 2 },
  { name: 'Drainage', duration: 2 },
  { name: 'Groundfloor slab', duration: 1 },
  { name: 'Brick wrap around', duration: 3 },
  { name: 'Scaff mats', duration: 2 },
  { name: 'Brickwork to cill height', duration: 4 },
  { name: 'Footlift scaffold', duration: 2 },
  { name: 'Brickwork to first', duration: 4 },
  { name: 'Scaffold 1st lift', duration: 2 },
  { name: 'Brickwork to joist', duration: 3 },
  { name: 'Joist', duration: 2 },
  { name: 'Strike scaffold birdcage and prop', duration: 1 },
  { name: 'Brickwork 2nd lift', duration: 4 },
  { name: 'Scaffold 2nd lift', duration: 2 },
  { name: 'Brickwork to roof', duration: 3 },
  { name: 'Scaffold roof lift and gables', duration: 2 },
  { name: 'Brickwork top out and plate', duration: 1 },
  { name: 'Trusses including upvc', duration: 4 },
  { name: 'Brickwork gables', duration: 3 },
  { name: 'Felt and batten', duration: 1 },
  { name: 'Roof tile', duration: 5 },
  { name: 'Gutter', duration: 1 },
  { name: 'Strike scaffold', duration: 2 },
  { name: 'Screed prep', duration: 1 },
  { name: 'Underfloor heating', duration: 1 },
  { name: 'Screed', duration: 1 },
  { name: 'Sound coat', duration: 1 },
  { name: 'Stairs', duration: 2 },
  { name: 'Windows', duration: 1 },
  { name: 'Top tack and metal stud', duration: 3 },
  { name: 'Plumber 1st fix', duration: 3 },
  { name: 'Electrical 1st fix', duration: 3 },
  { name: 'Carpenter 1st fix', duration: 2 },
  { name: 'Pre plaster inspection', duration: 1 },
  { name: 'Board and insulate', duration: 2 },
  { name: 'Dabbing', duration: 2 },
  { name: 'Plaster skim', duration: 4 },
  { name: 'Mist coat', duration: 1 },
  { name: 'Kitchen', duration: 2 },
  { name: 'Ceramic tiler', duration: 3 },
  { name: 'Carpenter 2nd fix', duration: 5 },
  { name: 'Plumber 2nd fix', duration: 3 },
  { name: 'Electrical 2nd fix', duration: 3 },
  { name: 'Patcher', duration: 1 },
  { name: 'Decorator', duration: 6 },
  { name: 'Plumb finals', duration: 1 },
  { name: 'Electrical final', duration: 1 },
  { name: 'Carpenter final', duration: 1 },
  { name: 'Build clean', duration: 1 },
  { name: 'Mastic', duration: 1 },
  { name: 'Airtest', duration: 1 },
  { name: 'Pre crc snag', duration: 1 },
  { name: 'Desnag', duration: 5 },
  { name: 'Wardrobe', duration: 1 },
  { name: 'Flooring', duration: 3 },
  { name: 'Dec snag', duration: 3 },
  { name: 'Magic man', duration: 1 },
  { name: 'Cml', duration: 1 },
  { name: 'Crc', duration: 1 },
];

export const getTotalDuration = (): number => {
  return BUILD_STAGES.reduce((total, stage) => total + stage.duration, 0);
};

export const getStageIndex = (stageName: string): number => {
  return BUILD_STAGES.findIndex(stage => stage.name === stageName);
};